package com.example.alpha_chat_native.ui.theme

import androidx.compose.ui.graphics.Color

// Material default colors (generated by Android Studio)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// ─── AlphaChat Brand Colors ───────────────────────────────────────────────────
// Source of truth — import from here instead of re-declaring in each screen file
val AlphaBackground   = Color(0xFF012106)  // Dark green background
val AlphaPrimary      = Color(0xFF07AD52)  // Neon green primary
val AlphaSecondary    = Color(0xFF04450F)  // Deep green secondary
val AlphaDark         = Color(0xFF020E2A)  // Near-black navy (background layer 2)
val AlphaNeonGreen    = Color(0xFF39FF14)  // Neon green accent (bright)
val AlphaGitHubBlack  = Color(0xFF24292e)  // GitHub brand button color